version: "2.1"
services:
  server:
    image: jetbrains/teamcity-server:latest
    ports:
      - "8112:8111"
    volumes:
      - ./teamcity-server/data:./teamcity-server/data
      - ./teamcity-server/logs:./teamcity-server/logs
    mem_limit: 2g
    restart: always
  agent:
    image: jetbrains/teamcity-agent:latest
    restart: always
    environment:
      - SERVER_URL=http://server:8111
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
